In [4]:
import pandas as pd
import datetime

# display all columns and rows
pd.set_option('display.max_colwidth',-1)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
users = [
'u004_rct@eureka',
'u005_rct@eureka',
'u006_rct@eureka',
'u007_rct@eureka',
'u008_rct@eureka',
'u009_rct@eureka',
'u010_rct@eureka',
'u011_rct@eureka',
'u012_rct@eureka',
'u013_rct@eureka',
'u014_rct@eureka',
'u015_rct@eureka',
'u016_rct@eureka',
'u017_rct@eureka',
'u018_rct@eureka',
'u019_rct@eureka',
'u020_rct@eureka',
'u021_rct@eureka',
'u022_rct@eureka',
'u023_rct@eureka',
'u024_rct@eureka',
'u025_rct@eureka',
'u026_rct@eureka',
'u027_rct@eureka',
'u028_rct@eureka',
'u029_rct@eureka',
'u030_rct@eureka',
'u031_rct@eureka',
'u032_rct@eureka',
'u033_rct@eureka',
'u034_rct@eureka',
'u035_rct@eureka',
'u036_rct@eureka',
'u037_rct@eureka',
'u038_rct@eureka',
'u039_rct@eureka',
'u040_rct@eureka',
'u041_rct@eureka',
'u042_rct@eureka',
'u043_rct@eureka',
'u044_rct@eureka',
'u045_rct@eureka',
'u046_rct@eureka',
'u047_rct@eureka',
'u048_rct@eureka',
'u049_rct@eureka',
'u050_rct@eureka',
'u051_rct@eureka',
'u052_rct@eureka',
'u053_rct@eureka',
'u054_rct@eureka',
'u055_rct@eureka',
'u056_rct@eureka',
'u057_rct@eureka',
'u058_rct@eureka',
'u059_rct@eureka',
'u060_rct@eureka',
'u061_rct@eureka',
'u062_rct@eureka',
'u063_rct@eureka',
'u064_rct@eureka',
'u065_rct@eureka',
'u066_rct@eureka',
'u067_rct@eureka',
'u068_rct@eureka',
'u069_rct@eureka',
'u070_rct@eureka',
'u071_rct@eureka',
'u072_rct@eureka',
'u073_rct@eureka',
]
print('total number of users:', len(users))

total number of users: 70

In [6]:
# get all processed feature tables
def get_table(csv_file):    
    csv_file = csv_file.drop(['Unnamed: 0'], axis=1)
    csv_file['time'] = pd.to_datetime(csv_file['time'])
    return csv_file

print(datetime.datetime.now())
calllog = get_table(pd.read_csv('table_calllog.csv'))
smslog = get_table(pd.read_csv('table_sms.csv'))
unlock = get_table(pd.read_csv('table_raw_unlock.csv'))
conver = get_table(pd.read_csv('table_conver.csv'))
sleep = get_table(pd.read_csv('table_sleep.csv'))
act = get_table(pd.read_csv('table_act.csv'))
light = get_table(pd.read_csv('table_light.csv'))
audio_amp = get_table(pd.read_csv('table_audio_amp.csv'))
audio_infer = get_table(pd.read_csv('table_audio_infer_new.csv'))
print(datetime.datetime.now())

ema = pd.read_csv('full_dataset.csv')
ema = ema[['study_id','eureka_id','day','ema_CALM','ema_DEPRESSED','ema_HARM','ema_HOPEFUL','ema_SEEING_THINGS','ema_SLEEPING','ema_SOCIAL','ema_STRESSED','ema_THINK','ema_VOICES','ema_neg_score','ema_pos_score','ema_resp_time_median']]

2020-08-05 20:53:36.599935
2020-08-05 21:01:26.397685

In [21]:
ema = pd.read_csv('full_dataset.csv')
ema = ema[['study_id','eureka_id','day','ema_CALM','ema_DEPRESSED','ema_HARM','ema_HOPEFUL','ema_SEEING_THINGS','ema_SLEEPING','ema_SOCIAL','ema_STRESSED','ema_THINK','ema_VOICES','ema_neg_score','ema_pos_score','ema_resp_time_median']]

In [22]:
days_string = []
for day in ema['day']:
    days_string.append(str(day))

In [23]:
ema_days = []
for day in days_string:
    ema_days.append(pd.to_datetime(day))
ema['day'] = ema_days
ema['ema_score'] = ema['ema_neg_score'] - ema['ema_pos_score']

In [24]:
ema = ema.dropna()

In [25]:
ema.head()

,study_id,eureka_id,day,ema_CALM,ema_DEPRESSED,ema_HARM,ema_HOPEFUL,ema_SEEING_THINGS,ema_SLEEPING,ema_SOCIAL,ema_STRESSED,ema_THINK,ema_VOICES,ema_neg_score,ema_pos_score,ema_resp_time_median,ema_score
6,-1,u004,2015-01-28,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,-1.0
13,-1,u004,2015-02-04,1.0,0.0,0.0,2.0,0.0,1.0,2.0,2.0,2.0,0.0,2.0,8.0,3.0,-6.0
15,-1,u004,2015-02-06,1.0,0.0,0.0,2.0,0.0,1.0,2.0,2.0,2.0,0.0,2.0,8.0,2.0,-6.0
22,-1,u004,2015-02-13,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,6.0,5.0,-5.0
25,-1,u004,2015-02-16,3.0,0.0,0.0,2.0,0.0,3.0,3.0,0.0,3.0,0.0,0.0,14.0,4.0,-14.0

In [69]:
def get_user_averages(behavior, behavior_name):
    user_mean_averages = []
#     user_std_averages = []
    for u in users:
        behavior_user = behavior.loc[behavior.uid == u]
        behavior_user = behavior_user.set_index('time')
        behavior_user = behavior_user[[behavior_name]]
        behavior_user = behavior_user.resample('D').sum()
        user_mean_averages.append(behavior_user[behavior_name].mean())
#         user_std_averages.append(behavior_user.std())
    return user_mean_averages
        
behaviors = [
             calllog,
             smslog,
             smslog,
             unlock, 
             conver, 
             sleep, 
             act,
             act,
             act,
             act,
             act,
             act,
             light, 
             audio_amp,
             audio_infer,
             audio_infer,
             audio_infer
            ]
behavior_names = [
                  'calllog',
                  'sms_in',
                  'sms_out',
                  'unlock',
                  'conver',
                  'sleep',
                  'act_invehicle',
                  'act_onbike',
                  'act_onfoot',
                  'act_still',
                  'act_tilting',
                  'act_unknown',
                  'light',
                  'audio_amp',
                  'audio_noise',
                  'audio_silence',
                  'audio_voice'                  
]

user_averages_table = pd.DataFrame()
for i in range(len(behaviors)):
    user_averages_table[behavior_names[i]] = get_user_averages(behaviors[i], behavior_names[i])
    print('finished behavior: ' + behavior_names[i])
    print(datetime.datetime.now()) 
    print()
user_averages_table.head()
user_averages_table.to_csv('feature_table_raw.csv')

finished behavior: calllog
2020-08-06 02:37:18.801794

finished behavior: sms_in
2020-08-06 02:38:06.014991

finished behavior: sms_out
2020-08-06 02:38:46.617757

finished behavior: unlock
2020-08-06 02:41:32.627650

finished behavior: conver
2020-08-06 02:42:50.836492

finished behavior: sleep
2020-08-06 02:44:50.371411

finished behavior: act_invehicle
2020-08-06 02:46:16.519862

finished behavior: act_onbike
2020-08-06 02:47:42.775719

finished behavior: act_onfoot
2020-08-06 02:49:08.704235

finished behavior: act_still
2020-08-06 02:50:34.785229

finished behavior: act_tilting
2020-08-06 02:52:01.051490

finished behavior: act_unknown
2020-08-06 02:53:28.226114

finished behavior: light
2020-08-06 02:55:27.864474

finished behavior: audio_amp
2020-08-06 02:57:33.849109

finished behavior: audio_noise
2020-08-06 02:59:37.395119

finished behavior: audio_silence
2020-08-06 03:01:36.622548

finished behavior: audio_voice
2020-08-06 03:03:35.647744

In [72]:
summary = user_averages_table.describe()

,calllog,sms_in,sms_out,unlock,conver,sleep,act_invehicle,act_onbike,act_onfoot,act_still,act_tilting,act_unknown,light,audio_amp,audio_noise,audio_silence,audio_voice
count,61.000000,66.000000,66.000000,70.000000,66.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,70.000000,7.000000e+01,7.000000e+01,70.000000,70.000000,70.000000
mean,633.958896,3.306973,3.072725,5060.147283,6378.267215,37665.134293,1451.297750,58.866296,919.382312,28770.871690,2182.295766,26461.039226,8.372464e+04,2.967325e+05,8093.235805,59789.598027,2775.407897
std,1137.471982,6.414580,7.625825,7423.040703,4988.588507,18854.048260,1484.202175,77.592756,1148.832409,12487.318781,2078.654271,14742.669690,1.457346e+05,2.948551e+05,8811.403051,26513.056902,3070.342378
min,0.000000,0.008889,0.000000,6.047073,60.000000,541.191524,0.000000,0.000000,0.000000,2845.294118,4.333333,4320.014706,4.241302e+02,8.549727e+02,59.649702,834.840259,3.333333
25%,46.665094,0.161054,0.000630,161.311475,1681.859043,31505.227806,141.192133,3.041409,42.842558,21234.067073,375.998536,18276.748556,7.573398e+03,2.630160e+04,3010.400742,60222.790253,204.143861
50%,242.727763,1.000000,0.114056,1805.435284,6395.794114,38023.090476,1093.265851,34.980287,541.819762,28839.279916,1733.837232,22949.568709,4.347618e+04,1.606631e+05,6365.285398,70453.120671,1340.156132
75%,921.577586,2.746691,1.862509,6460.328149,9071.887069,49094.761561,2272.829973,81.010471,1257.998590,37565.929783,3411.069128,28681.812313,8.763975e+04,5.343072e+05,9897.402747,75285.009998,4816.427429
max,8172.165025,36.717949,49.369231,30760.687970,23090.833333,81643.965517,5427.502564,359.735225,4694.130435,49873.000000,8039.501538,82705.000000,1.076462e+06,1.016473e+06,45809.284010,85841.861472,11924.662763

In [73]:
summary = user_averages_table.describe()

In [74]:
periods_columns = [c for c in user_averages_table.columns if 'sms' not in c and 'light' not in c and 'audio_amp' not in c]
for b in periods_columns:
    summary[b] = summary[b]/60.0
summary

,calllog,sms_in,sms_out,unlock,conver,sleep,act_invehicle,act_onbike,act_onfoot,act_still,act_tilting,act_unknown,light,audio_amp,audio_noise,audio_silence,audio_voice
count,1.016667,66.000000,66.000000,1.166667,1.100000,1.166667,1.166667,1.166667,1.166667,1.166667,1.166667,1.166667,7.000000e+01,7.000000e+01,1.166667,1.166667,1.166667
mean,10.565982,3.306973,3.072725,84.335788,106.304454,627.752238,24.188296,0.981105,15.323039,479.514528,36.371596,441.017320,8.372464e+04,2.967325e+05,134.887263,996.493300,46.256798
std,18.957866,6.414580,7.625825,123.717345,83.143142,314.234138,24.736703,1.293213,19.147207,208.121980,34.644238,245.711162,1.457346e+05,2.948551e+05,146.856718,441.884282,51.172373
min,0.000000,0.008889,0.000000,0.100785,1.000000,9.019859,0.000000,0.000000,0.000000,47.421569,0.072222,72.000245,4.241302e+02,8.549727e+02,0.994162,13.914004,0.055556
25%,0.777752,0.161054,0.000630,2.688525,28.030984,525.087130,2.353202,0.050690,0.714043,353.901118,6.266642,304.612476,7.573398e+03,2.630160e+04,50.173346,1003.713171,3.402398
50%,4.045463,1.000000,0.114056,30.090588,106.596569,633.718175,18.221098,0.583005,9.030329,480.654665,28.897287,382.492812,4.347618e+04,1.606631e+05,106.088090,1174.218678,22.335936
75%,15.359626,2.746691,1.862509,107.672136,151.198118,818.246026,37.880500,1.350175,20.966643,626.098830,56.851152,478.030205,8.763975e+04,5.343072e+05,164.956712,1254.750167,80.273790
max,136.202750,36.717949,49.369231,512.678133,384.847222,1360.732759,90.458376,5.995587,78.235507,831.216667,133.991692,1378.416667,1.076462e+06,1.016473e+06,763.488067,1430.697691,198.744379